### ISSUE TITLE
Incompatible with nystudio107/craft-autocomplete

### ISSUE THREAD

**Issue by roberttolton** [putyourlightson/craft-datastar#1]
### Bug Report

I'm not sure where this report should go, whether it's the Datastar plugin or Andrew's `craft-autocomplete` plugin, but when trying to generate the helper code I hit this stacktrace that mentioned Datastar. Disabling the Datastar plugin fixes it and the helper code generation works fine.

```
www-data@42b7baa36089:/app$ php craft autocomplete/generate
Exception 'yii\base\InvalidConfigException' with message 'The directory does not exist: '

in /app/vendor/yiisoft/yii2/web/AssetManager.php:238

Stack trace:
#0 /app/vendor/yiisoft/yii2/web/AssetManager.php(555): yii\web\AssetManager->checkBasePathPermission()
#1 /app/vendor/yiisoft/yii2/web/AssetManager.php(487): yii\web\AssetManager->publishDirectory('/app/vendor/put...', Array)
#2 /app/vendor/yiisoft/yii2/web/AssetBundle.php(181): yii\web\AssetManager->publish('/app/vendor/put...', Array)
#3 /app/vendor/yiisoft/yii2/web/AssetManager.php(294): yii\web\AssetBundle->publish(Object(yii\web\AssetManager))
#4 /app/vendor/yiisoft/yii2/web/AssetManager.php(265): yii\web\AssetManager->loadBundle('putyourlightson...', Array, true)
#5 /app/vendor/yiisoft/yii2/web/View.php(301): yii\web\AssetManager->getBundle('putyourlightson...')
#6 /app/vendor/craftcms/cms/src/web/View.php(2221): yii\web\View->registerAssetBundle('putyourlightson...', NULL)
#7 /app/vendor/putyourlightson/craft-datastar-module/src/Datastar.php(120): craft\web\View->registerAssetBundle('putyourlightson...')
#8 /app/vendor/putyourlightson/craft-datastar-module/src/Datastar.php(76): putyourlightson\datastar\Datastar->registerScript()
#9 /app/vendor/yiisoft/yii2/base/BaseObject.php(109): putyourlightson\datastar\Datastar->init()
#10 /app/vendor/yiisoft/yii2/base/Module.php(161): yii\base\BaseObject->__construct(Array)
#11 /app/vendor/putyourlightson/craft-datastar-module/src/Datastar.php(59): yii\base\Module->__construct('datastar-module')
#12 /app/vendor/putyourlightson/craft-datastar-module/src/Datastar.php(46): putyourlightson\datastar\Datastar::getInstance()
#13 /app/vendor/putyourlightson/craft-datastar/src/Plugin.php(19): putyourlightson\datastar\Datastar::bootstrap()
#14 /app/vendor/yiisoft/yii2/base/BaseObject.php(109): putyourlightson\datastar\plugin\Plugin->init()
#15 /app/vendor/yiisoft/yii2/base/Module.php(161): yii\base\BaseObject->__construct(Array)
#16 /app/vendor/craftcms/cms/src/base/Plugin.php(122): yii\base\Module->__construct('datastar', Object(craft\console\Application), Array)
#17 [internal function]: craft\base\Plugin->__construct('datastar', Object(craft\console\Application), Array)
#18 /app/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#19 /app/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('putyourlightson...', Array, Array)
#20 /app/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('putyourlightson...', Array, Array)
#21 /app/vendor/craftcms/cms/src/Craft.php(71): yii\BaseYii::createObject(Array, Array)
#22 /app/vendor/craftcms/cms/src/services/Plugins.php(945): Craft::createObject(Array, Array)
#23 /app/vendor/craftcms/cms/src/services/Plugins.php(233): craft\services\Plugins->createPlugin('datastar', Array)
#24 /app/vendor/craftcms/cms/src/base/ApplicationTrait.php(1631): craft\services\Plugins->loadPlugins()
#25 /app/vendor/craftcms/cms/src/console/Application.php(53): craft\console\Application->_postInit()
#26 /app/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#27 /app/vendor/yiisoft/yii2/base/Application.php(204): yii\base\BaseObject->__construct(Array)
#28 /app/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#29 [internal function]: yii\console\Application->__construct(Array)
#30 /app/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#31 /app/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('craft\\console\\A...', Array, Array)
#32 /app/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\console\\A...', Array, Array)
#33 /app/vendor/craftcms/cms/src/Craft.php(71): yii\BaseYii::createObject(Array, Array)
#34 /app/vendor/craftcms/cms/bootstrap/bootstrap.php(342): Craft::createObject(Array)
#35 /app/vendor/craftcms/cms/bootstrap/console.php(42): require('/app/vendor/cra...')
#36 /app/craft(12): require('/app/vendor/cra...')
#37 {main}
```

### Plugin Version

1.0.0-beta.2

### Craft CMS Version

5.5.7

### PHP Version

8.2

**Comment by khalwat** [comment]
Looks like @bencroker shouldn't be registering an asset bundle for console requests. Should be an easy fix.

**Comment by roberttolton** [comment]
> Looks like @bencroker shouldn't be registering an asset bundle for console requests. Should be an easy fix.

Sounds like it, as it's also happening in Tinkerwell.

**Comment by khalwat** [comment]
So I found a few errors actually:

ref: https://github.com/putyourlightson/craft-datastar/blob/develop/src/Plugin.php#L15C1-L21C1
```php
    public function init(): void
    {
        parent::init();

        Datastar::bootstrap();
    }
```

...should be:
```php
    public function init(): void
    {
        parent::init();
        // Only load for frontend requests
        if (Craft::$app->getRequest()->getIsSiteRequest()) {
            // Defer some setup tasks until Craft is fully initialized:
            Craft::$app->onInit(function() {
                Datastar::bootstrap();
            });
        }
    }
```

Firstly, it only loads for frontend (site) requests, because we don't want it loading in the CP for no reason. Any plugins that want to use it will require `putyourlightson/craft-datastar-module` directly, and will bootstrap the module themselves anyway.

Secondly, it ensures that Craft is fully initialized before you start accessing the view and registering scripts (which will cause Twig to get initialized early).

ref: https://github.com/putyourlightson/craft-datastar-module/blob/develop/src/Datastar.php#L36C1-L40C1
```php
    /**
     * The module settings.
     */
    private ?SettingsModel $_settings = null;
``` 

should be:
```php
    /**
     * The module settings.
     */
    private ?SettingsModel $settings = null;
```
...because it violates [PSR-12](https://www.php-fig.org/psr/psr-12/#43-properties-and-constants) 😉

**Comment by bencroker** [comment]
Thanks for the report, @roberttolton. I’ve made some changes in https://github.com/putyourlightson/craft-datastar-module/commit/595f8649b6731ff2b75a599318ac177e45a50f88, although I couldn’t replicate the error locally. I also integrated (some of) @khalwat’s suggestions 🙏
